version: 2

test: &test
  steps:
    - checkout

    - run:
        name: Run go mod
        command: |
          go mod download
          go mod vendor
    - run:
        name: Run vet
        command: go vet
    - run:
        name: Run lint
        command: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status $(go list ./... | grep -v /vendor/)
    - run:
        name: Run staticcheck
        command: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          GO111MODULE=off staticcheck ./...
    - run:
        name: Run tests
        command: go test -v

jobs:
  go-1.13-test:
    docker:
      - image: golang:1.15-stretch
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/y-yagi/jpcal
    <<: *test

workflows:
  version: 2
  build:
    jobs:
      - go-1.15-test
